name: xdatasets
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  - bottleneck
  - clisops
  - dask
  - dask-geopandas
  - geopandas
  - intake <2.0
  - intake-geopandas
  - intake-xarray >=0.6.1
  - ipykernel
  - ipython
  - jsonpickle
  - matplotlib-base
  - pint >=0.10
  - s3fs
  - tqdm
  - xagg
  - xarray >=2023.1
  - zarr
  # Dev tools and testing
  - black ==24.1.1
  - blackdoc ==0.3.9
  - bump-my-version >=0.17.1
  - coverage >=6.2.0,<8.0.0
#  - coveralls >=3.3.1  # newest coveralls binary is not compatible with latest coverage binary
  - flake8 >=6.1.0
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.9.0
  - isort ==5.13.2
  - pip >=23.3.0
  - pre-commit >=3.3.2
  - pytest >=7.3.1
  - pytest-cov >=4.0.0
  - tokenize-rt >=3.2.0
  - tox >=4.5.1
  - watchdog >=3.0.0
