name: xdatasets
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  # Main packages
  - bottleneck >=1.3.1
#  - cf-xarray >=0.6.1  # Was not included here, but appears in pyproject.toml
  - cftime >=1.4.1  # Is it needed? It's not used in the code.
  - clisops >=0.9.2
  - dask >=2.6
  - dask-geopandas >=0.4.1,<0.4.4
  - geopandas >=1.0.0,<1.1.0
  - intake
  - intake-geopandas
  - intake-xarray >=0.6.1,<2.0.0
  - ipykernel  # This should probably not be in the environment-dev.yml
  - ipython >=8.5.0  # This should probably not be in the environment-dev.yml
  - jsonpickle
  - matplotlib-base >=3.5.0  # This should probably not be in the environment-dev.yml
  - numpy >=1.25
  - pandas >=1.5.0
  - s3fs
  - scipy >=1.10.0
  - tqdm
  - xagg
  - xarray >=2023.1
  - zarr >=2.11.1
  # Dev tools and testing
  - pip >=25.0
  - bump-my-version >=0.30.1
  - black ==25.1.0
  - blackdoc ==0.3.9
  - coverage >=7.5.0
  - flake8 >=7.1.1
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.10.1,<4.0
  - isort ==6.0.0
  - mypy >=1.14.1
  - numpydoc >=1.8.0
  - pre-commit >=3.5.0
  - pytest >=8.3.2
  - pytest-cov >=5.0.0
  - ruff >=0.9.0
  - tokenize-rt >=3.2.0
  - tox >=4.24.1
  - watchdog >=4.0.0
