name: xdatasets
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  - bottleneck
  - clisops
  - dask
  - dask-geopandas
  - geopandas
  - intake
  - intake-geopandas
  - intake-xarray >=0.6.1
  - ipykernel
  - ipython
  - jsonpickle
  - matplotlib-base
  - pint >=0.10
  - s3fs
  - tqdm
  - xagg
  - xarray >=2023.1
  - zarr
  # Dev tools and testing
  - black >=23.11.0
  - blackdoc >=0.3.9
  - bump-my-version >=0.12.0
  - coverage >=6.2.0,<7.0.0
  - coveralls >=3.3.1
  - flake8 >=6.1.0
  - flake8-rst-docstrings >=0.3.0
  - flit
  - isort >=5.12.0
  - pip >=23.1.2
  - pre-commit >=3.3.2
  - pytest >=7.3.1
  - pytest-cov>=4.0.0
  - tokenize-rt>=3.2.0
  - tox >=4.5.1
  - watchdog >=3.0.0
