name: xdatasets
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  - bottleneck
  - clisops
  - dask
  - dask-geopandas
  - geopandas
  - intake <2.0.0  # Pinned until catalogs support v2.0 conventions. See: https://github.com/hydrologie/xdatasets/issues/82
  - intake-geopandas
  - intake-xarray >=0.6.1
  - ipykernel
  - ipython
  - jsonpickle
  - matplotlib-base
  - pint >=0.10
  - s3fs
  - tqdm
  - xagg
  - xarray >=2023.1
  - zarr
  # Dev tools and testing
  - pip >=24.0
  - bump-my-version >=0.22.0 # pinned until bump-my-version 0.23.0 is released
  - black ==24.4.2
  - blackdoc ==0.3.9
  - coverage >=7.5.0
  - coveralls >=4.0.0
  - flake8 >=7.0.0
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.9.0
  - isort ==5.13.2
  - pip >=23.3.0
  - pre-commit >=3.3.2
  - pytest >=7.3.1
  - pytest-cov >=4.0.0
  - ruff >=0.4.0
  - tokenize-rt >=3.2.0
  - tox >=4.15.1
  - watchdog >=3.0.0
